# Generated by Django 5.2.16 on 2026-08-03 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receivables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('other', 'Outro')], max_length=20)),
                ('notes', models.TextField()),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='receivables.receivable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('contacted', 'Contactado'), ('promise', 'Promessa registrada'), ('negotiating', 'Em negociacao'), ('paid', 'Pago'), ('unreachable', 'Nao localizado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('receivable', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection_status', to='receivables.receivable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negotiated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('installment_count', models.PositiveIntegerField()),
                ('periodicity_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluido'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='receivables.receivable')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='collections.paymentagreement')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promised_date', models.DateField()),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('kept', 'Cumprida'), ('broken', 'Quebrada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_promises', to='receivables.receivable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('negotiated_amount__gte', 0)), name='agreement_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gt', 0)), name='agreement_installments_positive'),
        ),
        migrations.AddConstraint(
            model_name='agreementinstallment',
            constraint=models.UniqueConstraint(fields=('agreement', 'number'), name='unique_agreement_installment'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['promised_date', 'status'], name='collections_promise_31cef0_idx'),
        ),
    ]
