# Generated by Codex on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("collections", "0003_negotiation_total_value")]

    operations = [
        migrations.AlterField(
            model_name="collectionstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("contacted", "Contactado"),
                    ("promise", "Promessa registrada"),
                    ("negotiating", "Em negociacao"),
                    ("paid", "Pago"),
                    ("unreachable", "Nao localizado"),
                    ("broken_promise", "Promessa não cumprida"),
                    ("broken_agreement", "Acordo não cumprido"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
