# Generated by Django 5.2.16 on 2026-08-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized_states',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='companies.state'),
        ),
    ]
