# Generated by Django 5.2.16 on 2026-08-27 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_authorized_states_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(default='', help_text='Use o formato internacional com +, código do país e DDD. Ex.: +5585999999999.', max_length=16, validators=[django.core.validators.RegexValidator(message='Informe o WhatsApp no formato internacional, por exemplo: +5585999999999.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='WhatsApp'),
        ),
    ]
