# Generated by Django 5.2.16 on 2026-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_whatsapp_number'),
        ('companies', '0002_company_origin_code_company_source_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_states',
            field=models.ManyToManyField(blank=True, help_text='Selecione os estados cujos dois relatórios devem ser enviados para este usuário.', related_name='report_recipients', to='companies.state', verbose_name='Estados dos relatórios por e-mail'),
        ),
    ]
