# Generated by Django 5.2.16 on 2026-08-03 22:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_number', models.CharField(max_length=100)),
                ('installment', models.CharField(default='1', max_length=30)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('financial_status', models.CharField(choices=[('open', 'Em aberto'), ('partially_paid', 'Parcialmente pago'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], default='open', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='customers.customer')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_receivables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['due_date', 'financial_status'], name='receivables_due_dat_6cb45a_idx'), models.Index(fields=['company', 'due_date'], name='receivables_company_ff3f58_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'title_number', 'installment'), name='unique_receivable_identity'), models.CheckConstraint(condition=models.Q(('outstanding_amount__gte', 0)), name='receivable_outstanding_non_negative')],
            },
        ),
    ]
