# Generated by Django 5.2.16 on 2026-08-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='source_overdue_days',
            field=models.PositiveIntegerField(default=0, help_text='Dias de atraso informados pela fonte (ATR)'),
        ),
    ]
