# Generated by Django 5.2.16 on 2026-08-27 14:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_receivable_source_overdue_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='balance_with_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='receivable',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='receivable',
            name='term_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
