# Generated by Django 5.2.16 on 2026-09-03 17:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_receivable_balance_with_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='agent_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='receivable',
            name='daily_interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='receivable',
            name='establishment_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='receivable',
            name='origin_establishment_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='receivable',
            name='seller',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='receivable',
            name='source_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
