services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cred_cobr
      POSTGRES_USER: cred_cobr
      POSTGRES_PASSWORD: change-me-local-only
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - reports_volume:/app/reports
      - imports_volume:/app/media/imports

  beat:
    build: .
    command: celery -A core beat -l INFO
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - reports_volume:/app/reports
      - imports_volume:/app/media/imports

volumes:
  postgres_data:
  redis_data:
  reports_volume:
  imports_volume:
