# Generated by Django 5.2.16 on 2026-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='origin_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='source_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='economicgroup',
            name='source_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
