# Generated by Django 5.2.16 on 2026-08-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexecution',
            name='overdue_band',
            field=models.CharField(blank=True, choices=[('1_10', 'Até 10 dias'), ('11_30', 'De 11 a 30 dias'), ('31_90', 'De 31 a 90 dias'), ('91_360', 'De 91 a 360 dias')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='report_type',
            field=models.CharField(choices=[('state_excel', 'Excel estadual consolidado'), ('band_excel', 'Excel por faixa'), ('executive_pdf', 'PDF executivo')], default='state_excel', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='reportexecution',
            constraint=models.UniqueConstraint(fields=('state', 'report_type', 'overdue_band', 'report_date'), name='unique_state_band_report_per_date'),
        ),
    ]
