# Generated by Django 5.2.16 on 2026-09-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportexecution_pdf_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexecution',
            name='report_type',
            field=models.CharField(choices=[('state_excel', 'Excel estadual consolidado'), ('upcoming_excel', 'Excel a vencer')], default='state_excel', max_length=30),
        ),
    ]
