# Generated by Django 5.2.16 on 2026-09-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('excel', 'Excel'), ('legacy', 'Banco legado')], max_length=20),
        ),
    ]
